name: deploy to uat

on:
  push:
    tags:
      - v*
env:
  SEARCH_DIR: ./.github/workflows

jobs: 
  DEPLOY:
    runs-on: ubuntu-latest
    steps:
      - id: set_output
        run: echo "::set-output name=appEnv::DEPLOY"
