name: deploy to uat

on:
  push:
    tags:
      - v*
env:
  SEARCH_DIR: ./.github/workflows

jobs: 
  DEPLOY:
    runs-on: ubuntu-latest
    steps:
      - id: set_output
        run: echo "::set-output name=appEnv::DEPLOY"
      - id: get_tag_name
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - id: set-iuput2 
        run: echo ${{ steps.get_tag_name.outputs.VERSION }}
